### ISSUE TITLE
Visual Studio Error 0x80004005

### ISSUE THREAD

**Issue by AndyTung401** [imhunterand/VBM-Valorant#13]
![image](https://user-images.githubusercontent.com/109213867/185294812-20f98739-bfc7-401a-b73c-0343fe0dbfd9.png)
All of the c++/c# file couldn't attach to VALORANT.exe. How can i solve it?

**Comment by imhunterand** [comment]
Hello @AndyTung401 ,

Error code: `0x80004005` means a file missing or can't be accessed.
In your case, probably the new Net Core SDK is not match. Try to install the new Runtime from:

[https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.0.4-download.md.](https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.0.4-download.md)
